import yfinance as yf
import os

from yfinance import tickers

ticker_list = ["B3SA3.SA", "AZUL4.SA", "CVCB3.SA", "HAPV3.SA", "PETR4.SA", "COGN3.SA", "BBDC4.SA", "ITSA4.SA",
               "ASAI3.SA",
               "ABEV3.SA", "CMIN3.SA", "ITUB4.SA", "LREN3.SA", "MGLU3.SA", "CRFB3.SA", "RAIL3.SA", "USIM5.SA",
               "VALE3.SA", "RAIZ4.SA", "MRVE3.SA", "GGBR4.SA", "RDOR3.SA", "ANIM3.SA", "RENT3.SA", "VAMO3.SA",
               "BRFS3.SA", "POMO4.SA", "CSNA3.SA", "ENEV3.SA", "JBSS3.SA", "IFCM3.SA", "BBAS3.SA", "EQTL3.SA",
               "CPLE6.SA", "GOLL4.SA", "VBBR3.SA", "CSAN3.SA", "BEEF3.SA", "PRIO3.SA", "NTCO3.SA", "EMBR3.SA",
               "MULT3.SA", "PETR3.SA", "MOVI3.SA", "ELET3.SA", "PCAR3.SA", "ONCO3.SA", "GOAU4.SA", "JFEN3.SA",
               "PETZ3.SA", "BRKM5.SA", "BPAC11.SA", "HYPE3.SA", "RADL3.SA", "YDUQ3.SA", "SRNA3.SA", "GMAT3.SA",
               "CMIG4.SA", "CSMG3.SA", "UGPA3.SA", "GFSA3.SA", "CPLE3.SA", "CYRE3.SA", "AMER3.SA", "CCRO3.SA",
               "SBSP3.SA", "ALOS3.SA", "MRFG3.SA", "TIMS3.SA", "BBDC3.SA", "RAPT4.SA", "SIMH3.SA", "LWSA3.SA",
               "AURE3.SA", "DXCO3.SA", "BRAV3.SA", "QUAL3.SA", "TOTS3.SA", "STBP3.SA", "KLBN11.SA", "VVEO3.SA",
               "JHSF3.SA", "EZTC3.SA", "TEND3.SA", "WEGE3.SA", "BRAP4.SA", "SMFT3.SA", "BHIA3.SA", "DIRR3.SA",
               "ECOR3.SA", "CXSE3.SA", "SUZB3.SA", "CBAV3.SA", "AESB3.SA", "CEAB3.SA", "CURY3.SA", "AZZA3.SA",
               "CASH3.SA", "RECV3.SA", "BBSE3.SA", "ALPA4.SA", "AZEV4.SA", "VIVA3.SA", "IGTI11.SA", "IGTI11.SA",
               "PSSA3.SA", "SAPR11.SA", "VIVT3.SA", "SLCE3.SA", "TRPL4.SA", "ENGI11.SA", "CLSA3.SA", "SBFG3.SA",
               "SMTO3.SA", "LJQQ3.SA", "CPFE3.SA", "BRSR6.SA", "SAPR4.SA", "GGPS3.SA", "POSI3.SA", "FLRY3.SA",
               "MELK3.SA", "FRAS3.SA", "RCSL3.SA", "MLAS3.SA", "SANB11.SA", "BPAN4.SA", "TAEE11.SA", "TTEN3.SA",
               "LPSB3.SA", "OIBR3.SA", "ELET6.SA", "PORT3.SA", "FIQE3.SA", "IRBR3.SA", "LIGT3.SA", "JSLG3.SA",
               "VLID3.SA", "MILS3.SA", "ITUB3.SA", "INTB3.SA", "EGIE3.SA", "SEER3.SA", "KLBN4.SA", "TRAD3.SA",
               "GUAR3.SA", "MTRE3.SA", "HBSA3.SA", "RANI3.SA", "MDIA3.SA", "DASA3.SA", "MYPK3.SA", "ORVR3.SA",
               "HBOR3.SA", "AZEV3.SA", "GRND3.SA", "CSED3.SA", "TRIS3.SA", "KEPL3.SA", "PDGR3.SA", "EVEN3.SA",
               "LAVV3.SA", "BMGB4.SA", "MEAL3.SA", "ODPV3.SA", "NGRD3.SA", "ABCB4.SA", "SEQL3.SA", "SYNE3.SA",
               "ALUP11.SA", "ENJU3.SA", "KRSA3.SA", "PGMN3.SA", "ARML3.SA", "AMBP3.SA", "OPCT3.SA", "AMAR3.SA",
               "NEOE3.SA", "MBLY3.SA", "VULC3.SA", "PLPL3.SA", "BRIT3.SA", "RCSL4.SA", "LEVE3.SA", "SHOW3.SA",
               "BRBI11.SA", "SOJA3.SA", "PNVL3.SA", "PTBL3.SA", "MDNE3.SA", "ZAMP3.SA", "FESA4.SA", "POMO3.SA",
               "USIM3.SA", "TUPY3.SA", "HBRE3.SA", "UNIP6.SA", "TFCO4.SA", "RAPT3.SA", "WIZC3.SA", "CAML3.SA",
               "JALL3.SA", "LAND3.SA", "BLAU3.SA", "AERI3.SA", "ALPK3.SA", "SHUL4.SA", "RNEW4.SA", "TASA4.SA",
               "LOGG3.SA", "AGRO3.SA", "MATD3.SA", "SAPR3.SA", "VTRU3.SA", "ETER3.SA", "PRNR3.SA", "RNEW3.SA",
               "DESK3.SA", "KLBN3.SA", "TAEE4.SA", "TECN3.SA", "TPIS3.SA", "ROMI3.SA", "IGTI3.SA", "IGTI3.SA",
               "LUPA3.SA", "VITT3.SA", "ITSA3.SA", "CMIG3.SA", "BMOB3.SA", "TGMA3.SA", "DEXP3.SA", "PFRM3.SA",
               "AGXY3.SA", "INEP3.SA", "ALLD3.SA", "WHRL3.SA", "RPMG3.SA", "BRAP3.SA", "WHRL4.SA", "ELMD3.SA",
               "BIOM3.SA", "TCSA3.SA", "PINE4.SA", "ESPA3.SA", "ESTR4.SA", "DMVF3.SA", "TAEE3.SA", "CTSA4.SA",
               "VIVR3.SA", "CSUD3.SA", "PMAM3.SA", "EUCA4.SA", "SANB4.SA", "WEST3.SA", "LVTC3.SA", "DOTZ3.SA",
               "GGBR3.SA", "BRKM3.SA", "SANB3.SA", "BOBR4.SA", "GOAU3.SA", "INEP4.SA", "ATMP3.SA", "HAGA4.SA",
               "PDTC3.SA", "AMAR11.SA", "LOGN3.SA", "COCE5.SA", "UCAS3.SA", "BMEB4.SA", "EPAR3.SA", "CAMB3.SA",
               "TASA3.SA", "BRSR3.SA", "AALR3.SA", "SNSY5.SA", "CEBR3.SA", "BEES3.SA", "RSID3.SA", "VSTE3.SA",
               "ENGI4.SA", "EALT4.SA", "ALUP4.SA", "UNIP3.SA", "OSXB3.SA", "CEBR6.SA", "BPAC3.SA", "RNEW11.SA",
               "CGRA4.SA", "CRPG6.SA", "BAZA3.SA", "PTNT4.SA", "ALPA3.SA", "AVLL3.SA", "ENGI3.SA", "CLSC4.SA",
               "EMAE4.SA", "TRPL3.SA", "RSUL4.SA", "EQPA3.SA", "DEXP4.SA", "MNDL3.SA", "OFSA3.SA", "MWET4.SA",
               "BPAC5.SA", "NUTR3.SA", "OIBR4.SA", "BEES4.SA", "RDNI3.SA", "SCAR3.SA", "AZEV11.SA", "BSLI3.SA",
               "CTSA3.SA", "HOOT4.SA", "ALUP3.SA", "CEBR5.SA", "BAHI3.SA", "NEXP3.SA", "BGIP4.SA", "EQMA3B.SA",
               "TELB3.SA", "PINE3.SA", "EALT3.SA", "TELB4.SA", "HETA4.SA", "CGAS5.SA", "MRSA3B.SA", "CRPG5.SA",
               "MNPR3.SA", "BIOM11.SA", "MTSA4.SA", "WLMM4.SA", "MGEL4.SA", "BMKS3.SA", "PEAB4.SA", "UNIP5.SA",
               "EKTR4.SA", "GEPA4.SA", "BSLI4.SA", "REDE3.SA", "ELET5.SA", "BMEB3.SA", "GEPA3.SA", "CTKA4.SA",
               "BRKM6.SA", "IGTI4.SA", "IGTI4.SA", "NINJ3.SA", "DOHL4.SA", "HAGA3.SA", "FRIO3.SA", "HBTS5.SA",
               "AHEB3.SA", "CGRA3.SA", "EUCA3.SA", "PTNT3.SA", "RPAD6.SA", "FHER3.SA", "ATOM3.SA", "PPLA11.SA",
               "PATI3.SA", "CBEE3.SA", "NORD3.SA", "JOPA3.SA", "SNSY3.SA", "BAUH4.SA", "PEAB3.SA", "AHEB5.SA",
               "LUXM4.SA", "CPLE5.SA", "TEKA4.SA", "CEDO4.SA", "BMIN4.SA", "PLAS3.SA", "PINE11.SA", "GSHP3.SA",
               "PSVM11.SA", "MRSA6B.SA", "ENMT4.SA", "SOND5.SA", "CEDO3.SA", "BMIN3.SA", "FESA3.SA", "BALM3.SA",
               "FIEI3.SA", "MAPT4.SA", "RPAD5.SA", "CEEB3.SA", "BALM4.SA", "CLSC3.SA", "PATI4.SA", "BGIP3.SA",
               "USIM6.SA", "BDLL4.SA", "BDLL3.SA", "MERC4.SA", "CGAS3.SA", "MAPT3.SA", "WLMM3.SA", "RRRP3.SA",
               "MRSA5B.SA", "DTCY3.SA", "AFLT3.SA", "CEED3.SA", "COCE3.SA", "BNBR3.SA", "APER3.SA", "BRSR5.SA",
               "CEEB5.SA", "RPAD3.SA"]

nasdaq = ["AACG", "AADI", "AADR", "AAL", "AAME", "AAOI", "AAON", "AAPB", "AAPD", "AAPL", "AAPU", "AAXJ", "ABAT", "ABCL",
          "ABCS", "ABEO", "ABL", "ABLLL", "ABLLW", "ABLV", "ABLVW", "ABNB", "ABOS", "ABSI", "ABTS", "ABUS", "ABVC",
          "ABVE", "ABVEW", "ABVX", "ACAB", "ACABU", "ACABW", "ACAD", "ACB", "ACCD", "ACDC", "ACET", "ACGL", "ACGLN",
          "ACGLO", "ACHC", "ACHL", "ACHV", "ACIC", "ACIU", "ACIW", "ACLS", "ACLX", "ACMR", "ACNB", "ACNT", "ACON",
          "ACONW", "ACRS", "ACRV", "ACST", "ACT", "ACTG", "ACTU", "ACVA", "ACWI", "ACWX", "ACXP", "ADAG", "ADAP",
          "ADBE", "ADD", "ADEA", "ADGM", "ADI", "ADIL", "ADMA", "ADN", "ADNWW", "ADP", "ADPT", "ADSE", "ADSEW", "ADSK",
          "ADTN", "ADTX", "ADUS", "ADV", "ADVM", "ADVWW", "ADXN", "AEAE", "AEAEU", "AEAEW", "AEHL", "AEHR", "AEI",
          "AEIS", "AEMD", "AENT", "AENTW", "AEP", "AERT", "AERTW", "AEYE", "AFBI", "AFCG", "AFJK", "AFJKR", "AFJKU",
          "AFMD", "AFRI", "AFRIW", "AFRM", "AFYA", "AGAE", "AGBA", "AGBAW", "AGEN", "AGFY", "AGIO", "AGIX", "AGMH",
          "AGMI", "AGNC", "AGNCL", "AGNCM", "AGNCN", "AGNCO", "AGNCP", "AGNG", "AGRI", "AGYS", "AGZD", "AHCO", "AHG",
          "AIA", "AIEV", "AIFF", "AIHS", "AILE", "AILEW", "AIMAU", "AIMAW", "AIMBU", "AIMD", "AIMDW", "AIOT", "AIP",
          "AIPI", "AIQ", "AIRE", "AIRG", "AIRJ", "AIRJW", "AIRL", "AIRR", "AIRS", "AIRT", "AIRTP", "AISP", "AISPW",
          "AITR", "AITRR", "AITRU", "AIXI", "AKAM", "AKAN", "AKBA", "AKRO", "AKTS", "AKTX", "AKYA", "ALAB", "ALAR",
          "ALBT", "ALCE", "ALCO", "ALCY", "ALCYU", "ALCYW", "ALDX", "ALEC", "ALF", "ALFUU", "ALFUW", "ALGM", "ALGN",
          "ALGS", "ALGT", "ALHC", "ALKS", "ALKT", "ALLK", "ALLO", "ALLR", "ALLT", "ALMS", "ALNT", "ALNY", "ALOT",
          "ALPP", "ALRM", "ALRN", "ALRS", "ALSA", "ALSAR", "ALSAU", "ALSAW", "ALT", "ALTI", "ALTO", "ALTR", "ALTS",
          "ALTY", "ALVO", "ALVOW", "ALVR", "ALXO", "ALZN", "AMAL", "AMAT", "AMBA", "AMCX", "AMD", "AMDL", "AMDS",
          "AMED", "AMGN", "AMID", "AMIX", "AMKR", "AMLI", "AMLX", "AMPG", "AMPGW", "AMPH", "AMPL", "AMRK", "AMRN",
          "AMRX", "AMSC", "AMSF", "AMST", "AMTX", "AMWD", "AMZD", "AMZN", "AMZU", "AMZZ", "ANAB", "ANDE", "ANEB",
          "ANGH", "ANGHW", "ANGI", "ANGL", "ANGO", "ANIK", "ANIP", "ANIX", "ANL", "ANNX", "ANSC", "ANSCU", "ANSCW",
          "ANSS", "ANTE", "ANTX", "ANY", "AOSL", "AOTG", "AOUT", "APA", "APCX", "APCXW", "APDN", "APEI", "APGE", "API",
          "APLD", "APLM", "APLMW", "APLS", "APLT", "APM", "APOG", "APP", "APPF", "APPN", "APPS", "APRE", "APTO", "APVO",
          "APWC", "APXI", "APXIU", "APXIW", "APYX", "AQB", "AQMS", "AQST", "AQU", "AQUNR", "AQUNU", "AQWA", "ARAY",
          "ARBB", "ARBE", "ARBEW", "ARBK", "ARBKL", "ARCB", "ARCC", "ARCT", "ARDX", "AREB", "AREBW", "AREC", "ARGX",
          "ARHS", "ARKO", "ARKOW", "ARKR", "ARLP", "ARM", "AROW", "ARQ", "ARQQ", "ARQQW", "ARQT", "ARRY", "ARTL",
          "ARTNA", "ARTV", "ARTW", "ARVN", "ARVR", "ARWR", "ASET", "ASLE", "ASMB", "ASML", "ASND", "ASNS", "ASO",
          "ASPI", "ASPS", "ASRT", "ASRV", "ASST", "ASTC", "ASTE", "ASTH", "ASTI", "ASTL", "ASTLW", "ASTS", "ASUR",
          "ASYS", "ATAI", "ATAT", "ATCOL", "ATEC", "ATER", "ATEX", "ATGL", "ATHA", "ATHE", "ATIF", "ATLC", "ATLCL",
          "ATLCP", "ATLCZ", "ATLO", "ATLX", "ATMC", "ATMCR", "ATMCU", "ATMCW", "ATMV", "ATMVR", "ATMVU", "ATNF",
          "ATNFW", "ATNI", "ATOM", "ATOS", "ATPC", "ATRA", "ATRC", "ATRO", "ATSG", "ATXG", "ATXI", "ATXS", "ATYR",
          "AUBN", "AUDC", "AUID", "AUMI", "AUPH", "AUR", "AURA", "AUROW", "AUTL", "AUUD", "AUUDW", "AVAH", "AVAV",
          "AVBP", "AVDL", "AVDX", "AVGO", "AVGR", "AVGX", "AVIR", "AVNW", "AVO", "AVPT", "AVPTW", "AVT", "AVTE", "AVTX",
          "AVXC", "AVXL", "AWH", "AWRE", "AXDX", "AXGN", "AXNX", "AXON", "AXSM", "AXTI", "AY", "AYRO", "AYTU", "AZ",
          "AZI", "AZN", "AZPN", "AZTA", "BABX", "BACK", "BAER", "BAERW", "BAFN", "BAND", "BANF", "BANFP", "BANL",
          "BANR", "BANX", "BAOS", "BASE", "BATRA", "BATRK", "BAYA", "BAYAR", "BAYAU", "BBCP", "BBGI", "BBH", "BBIO",
          "BBLG", "BBLGW", "BBSI", "BCAB", "BCAL", "BCAN", "BCAX", "BCBP", "BCDA", "BCG", "BCGWW", "BCLI", "BCML",
          "BCOV", "BCOW", "BCPC", "BCRX", "BCSA", "BCSAU", "BCSAW", "BCTX", "BCTXW", "BCYC", "BDGS", "BDMD", "BDMDW",
          "BDRX", "BDSX", "BDTX", "BEAM", "BEAT", "BEATW", "BECN", "BEEM", "BEEZ", "BELFA", "BELFB", "BELT", "BENF",
          "BENFW", "BETR", "BETRW", "BFC", "BFIN", "BFRG", "BFRGW", "BFRI", "BFRIW", "BFST", "BGC", "BGFV", "BGLC",
          "BGM", "BGNE", "BGRN", "BGRO", "BHAC", "BHACU", "BHACW", "BHAT", "BHF", "BHFAL", "BHFAM", "BHFAN", "BHFAO",
          "BHFAP", "BHIL", "BHRB", "BIAF", "BIAFW", "BIB", "BIDU", "BIGC", "BIIB", "BILI", "BIOA", "BIOR", "BIOX",
          "BIRD", "BIS", "BITF", "BITS", "BIVI", "BJDX", "BJK", "BJRI", "BKCH", "BKHA", "BKHAR", "BKHAU", "BKIV",
          "BKNG", "BKR", "BKWO", "BKYI", "BL", "BLAC", "BLACR", "BLACU", "BLACW", "BLBD", "BLBX", "BLCN", "BLCR",
          "BLDE", "BLDEW", "BLDP", "BLEU", "BLEUR", "BLEUU", "BLEUW", "BLFS", "BLFY", "BLIN", "BLKB", "BLLD", "BLMN",
          "BLMZ", "BLNK", "BLRX", "BLTE", "BLUE", "BLZE", "BMBL", "BMDL", "BMEA", "BMR", "BMRA", "BMRC", "BMRN", "BNAI",
          "BNAIW", "BND", "BNDW", "BNDX", "BNGO", "BNIX", "BNIXR", "BNIXW", "BNOX", "BNR", "BNRG", "BNTC", "BNTX",
          "BNZI", "BNZIW", "BOCN", "BOCNU", "BOCNW", "BOF", "BOKF", "BOLD", "BOLT", "BON", "BOOM", "BOSC", "BOTJ",
          "BOTT", "BOTZ", "BOWN", "BOWNR", "BOWNU", "BOXL", "BPMC", "BPOP", "BPOPM", "BPRN", "BPTH", "BPYPM", "BPYPN",
          "BPYPO", "BPYPP", "BRAC", "BRACR", "BRACU", "BRAG", "BREA", "BRFH", "BRHY", "BRID", "BRKH", "BRKHU", "BRKHW",
          "BRKL", "BRKR", "BRLS", "BRLSW", "BRLT", "BRNS", "BRNY", "BROG", "BROGW", "BRRR", "BRTR", "BRTX", "BRY",
          "BRZE", "BSBK", "BSCO", "BSCP", "BSCQ", "BSCR", "BSCS", "BSCT", "BSCU", "BSCV", "BSCW", "BSCX", "BSCY",
          "BSET", "BSFC", "BSIIU", "BSJO", "BSJP", "BSJQ", "BSJR", "BSJS", "BSJT", "BSJU", "BSJV", "BSJW", "BSLK",
          "BSLKW", "BSMO", "BSMP", "BSMQ", "BSMR", "BSMS", "BSMT", "BSMU", "BSMV", "BSMW", "BSMY", "BSRR", "BSSX",
          "BSVN", "BSVO", "BSY", "BTAI", "BTBD", "BTBDW", "BTBT", "BTCS", "BTCT", "BTCTW", "BTDR", "BTF", "BTFX", "BTM",
          "BTMD", "BTMWW", "BTOC", "BTOG", "BTSG", "BTSGU", "BUFC", "BUG", "BUJA", "BUJAR", "BUJAU", "BUJAW", "BULD",
          "BUSE", "BVFL", "BVS", "BWAY", "BWB", "BWBBP", "BWEN", "BWFG", "BWIN", "BWMN", "BYFC", "BYND", "BYNO",
          "BYNOU", "BYNOW", "BYRN", "BYSI", "BYU", "BZ", "BZFD", "BZFDW", "BZUN", "CA", "CAAS", "CABA", "CAC", "CACC",
          "CADL", "CAFG", "CAKE", "CALC", "CALM", "CALY", "CAMT", "CAN", "CANC", "CANQ", "CAPNU", "CAPR", "CAPT",
          "CAPTW", "CAR", "CARA", "CARE", "CARG", "CARM", "CART", "CARV", "CARZ", "CASH", "CASI", "CASS", "CASY",
          "CATH", "CATY", "CBAN", "CBAT", "CBFV", "CBNK", "CBRG", "CBRGU", "CBRL", "CBSH", "CBUS", "CCAP", "CCB",
          "CCBG", "CCCC", "CCCS", "CCD", "CCEC", "CCEP", "CCG", "CCGWW", "CCIX", "CCIXU", "CCIXW", "CCLD", "CCLDO",
          "CCLDP", "CCNE", "CCNEP", "CCNR", "CCOI", "CCRN", "CCSB", "CCSI", "CCSO", "CCTG", "CCTS", "CCTSU", "CCTSW",
          "CDAQ", "CDAQU", "CDAQW", "CDC", "CDIO", "CDIOW", "CDL", "CDLX", "CDMO", "CDNA", "CDNS", "CDRO", "CDROW",
          "CDT", "CDTG", "CDTTW", "CDTX", "CDW", "CDXC", "CDXS", "CDZI", "CDZIP", "CEAD", "CEADW", "CECO", "CEFA",
          "CEG", "CELC", "CELH", "CELU", "CELUW", "CELZ", "CENN", "CENT", "CENTA", "CENX", "CEP", "CERO", "CEROW",
          "CERS", "CERT", "CETX", "CETY", "CEVA", "CFA", "CFB", "CFBK", "CFFI", "CFFN", "CFFS", "CFFSU", "CFFSW",
          "CFLT", "CFO", "CFSB", "CG", "CGABL", "CGBD", "CGBDL", "CGBS", "CGBSW", "CGC", "CGEM", "CGEN", "CGNT", "CGNX",
          "CGO", "CGON", "CGTX", "CHCI", "CHCO", "CHDN", "CHEF", "CHEK", "CHI", "CHKP", "CHMG", "CHNR", "CHPS", "CHR",
          "CHRD", "CHRS", "CHRW", "CHSCL", "CHSCM", "CHSCN", "CHSCO", "CHSCP", "CHSN", "CHTR", "CHUY", "CHW", "CHX",
          "CHY", "CIBR", "CID", "CIFR", "CIFRW", "CIGI", "CIL", "CINF", "CING", "CINGW", "CISO", "CISS", "CITE",
          "CITEU", "CITEW", "CIVB", "CIZ", "CJET", "CJJD", "CKPT", "CLAR", "CLBK", "CLBT", "CLDX", "CLEU", "CLFD",
          "CLGN", "CLIR", "CLLS", "CLMB", "CLMT", "CLNE", "CLNN", "CLNNW", "CLOA", "CLOD", "CLOU", "CLOV", "CLPS",
          "CLPT", "CLRB", "CLRC", "CLRCR", "CLRCU", "CLRCW", "CLRO", "CLSD", "CLSK", "CLSM", "CLST", "CLWT", "CLYM",
          "CMAX", "CMAXW", "CMBM", "CMCO", "CMCSA", "CMCT", "CME", "CMLS", "CMMB", "CMND", "CMPO", "CMPOW", "CMPR",
          "CMPS", "CMPX", "CMRX", "CMTL", "CNCR", "CNDT", "CNET", "CNEY", "CNFR", "CNFRZ", "CNOB", "CNOBP", "CNSL",
          "CNSP", "CNTA", "CNTB", "CNTM", "CNTX", "CNTY", "CNVS", "CNXC", "CNXN", "COCH", "COCHW", "COCO", "COCP",
          "CODA", "CODX", "COEP", "COEPW", "COFS", "COGT", "COHU", "COIN", "COKE", "COLB", "COLL", "COLM", "COMM",
          "COMT", "CONI", "CONL", "COO", "COOP", "COOT", "COOTW", "COPJ", "COPP", "CORT", "CORZ", "CORZW", "CORZZ",
          "COSM", "COST", "COWG", "COWS", "COYA", "CPB", "CPBI", "CPHC", "CPIX", "CPLS", "CPOP", "CPRT", "CPRX", "CPSH",
          "CPSS", "CPTN", "CPTNW", "CPZ", "CRAI", "CRBP", "CRBU", "CRCT", "CRDF", "CRDL", "CRDO", "CREG", "CRESW",
          "CRESY", "CREV", "CREVW", "CREX", "CRGO", "CRGOW", "CRGX", "CRIS", "CRKN", "CRMD", "CRML", "CRMLW", "CRMT",
          "CRNC", "CRNT", "CRNX", "CRON", "CROX", "CRSP", "CRSR", "CRTO", "CRUS", "CRVL", "CRVO", "CRVS", "CRWD",
          "CRWS", "CSA", "CSB", "CSBR", "CSCI", "CSCO", "CSF", "CSGP", "CSGS", "CSIQ", "CSLM", "CSLMR", "CSLMU",
          "CSLMW", "CSLR", "CSLRW", "CSPI", "CSQ", "CSTE", "CSTL", "CSWC", "CSWCZ", "CSWI", "CSX", "CTAS", "CTBI",
          "CTCX", "CTCXW", "CTEC", "CTHR", "CTKB", "CTLP", "CTMX", "CTNM", "CTNT", "CTOR", "CTRM", "CTRN", "CTSH",
          "CTSO", "CTXR", "CUB", "CUBA", "CUBWU", "CUBWW", "CUE", "CURI", "CURIW", "CURR", "CUTR", "CVAC", "CVBF",
          "CVCO", "CVGI", "CVGW", "CVKD", "CVLT", "CVRX", "CVV", "CWBC", "CWCO", "CWD", "CWST", "CXAI", "CXAIW", "CXDO",
          "CXSE", "CYBR", "CYCC", "CYCCP", "CYCN", "CYN", "CYRX", "CYTH", "CYTHW", "CYTK", "CYTO", "CZAR", "CZFS",
          "CZNC", "CZR", "CZWI", "DADA", "DAIO", "DAKT", "DALI", "DALN", "DAPP", "DARE", "DASH", "DATS", "DATSW",
          "DAVE", "DAVEW", "DAWN", "DAX", "DBGI", "DBGIW", "DBVT", "DBX", "DCAP", "DCBO", "DCGO", "DCOM", "DCOMG",
          "DCOMP", "DCTH", "DDI", "DDIV", "DDOG", "DECA", "DECAU", "DECAW", "DECO", "DEMZ", "DENN", "DERM", "DFGP",
          "DFGX", "DFLI", "DFLIW", "DGCB", "DGHI", "DGICA", "DGICB", "DGII", "DGLY", "DGRE", "DGRS", "DGRW", "DH",
          "DHAI", "DHAIW", "DHC", "DHCNI", "DHCNL", "DHIL", "DIBS", "DIOD", "DIST", "DISTR", "DISTW", "DIVD", "DJCO",
          "DJT", "DJTWW", "DKNG", "DLHC", "DLO", "DLPN", "DLTH", "DLTR", "DMAC", "DMAT", "DMLP", "DMRC", "DMXF", "DNLI",
          "DNTH", "DNUT", "DOCU", "DOGZ", "DOMH", "DOMO", "DOOO", "DORM", "DOX", "DOYU", "DPCS", "DPCSU", "DPCSW",
          "DPRO", "DRCT", "DRIO", "DRIV", "DRMA", "DRMAW", "DRRX", "DRS", "DRTS", "DRTSW", "DRUG", "DRVN", "DSGN",
          "DSGR", "DSGX", "DSP", "DSWL", "DSY", "DSYWW", "DTCK", "DTCR", "DTI", "DTIL", "DTSQ", "DTSQR", "DTSQU",
          "DTSS", "DTST", "DTSTW", "DUET", "DUETU", "DUETW", "DUKH", "DUKX", "DUO", "DUOL", "DUOT", "DVAL", "DVAX",
          "DVLU", "DVOL", "DVY", "DWAS", "DWAW", "DWSH", "DWSN", "DWUS", "DXCM", "DXJS", "DXLG", "DXPE", "DXR", "DYAI",
          "DYCQ", "DYCQR", "DYCQU", "DYFI", "DYN", "DYNI", "DYTA", "EA", "EAST", "EBAY", "EBC", "EBIZ", "EBMT", "EBON",
          "EBTC", "ECBK", "ECDA", "ECDAW", "ECOR", "ECOW", "ECPG", "ECX", "ECXWW", "EDAP", "EDBL", "EDBLW", "EDIT",
          "EDOC", "EDRY", "EDSA", "EDTK", "EDUC", "EEFT", "EEIQ", "EEMA", "EFAS", "EFOI", "EFRA", "EFSC", "EFSCP",
          "EGAN", "EGBN", "EGHT", "EH", "EHGO", "EHLS", "EHTH", "EJH", "EKG", "EKSO", "ELAB", "ELBM", "ELDN", "ELEV",
          "ELSE", "ELTK", "ELTX", "ELUT", "ELVA", "ELVN", "ELWS", "EM", "EMB", "EMBC", "EMCB", "EMCG", "EMCGR", "EMCGU",
          "EMCGW", "EMEQ", "EMIF", "EMKR", "EML", "EMXC", "EMXF", "ENG", "ENGN", "ENGNW", "ENLT", "ENLV", "ENPH",
          "ENSC", "ENSG", "ENTA", "ENTG", "ENTO", "ENTX", "ENVB", "ENVX", "ENZL", "EOLS", "EOSE", "EOSEW", "EPIX",
          "EPOW", "EPRX", "EPSN", "EQ", "EQIX", "EQRR", "ERAS", "ERET", "ERIC", "ERIE", "ERII", "ERNA", "ERNZ", "ESCA",
          "ESEA", "ESGD", "ESGE", "ESGL", "ESGLW", "ESGR", "ESGRO", "ESGRP", "ESGU", "ESHA", "ESHAR", "ESLA", "ESLAW",
          "ESLT", "ESMV", "ESOA", "ESPO", "ESPR", "ESQ", "ESSA", "ESTA", "ETEC", "ETHA", "ETNB", "ETON", "ETSY", "EU",
          "EUDA", "EUDAW", "EUFN", "EURK", "EURKR", "EURKU", "EVAX", "EVCM", "EVER", "EVGN", "EVGO", "EVGOW", "EVGR",
          "EVGRU", "EVGRW", "EVLV", "EVLVW", "EVMT", "EVO", "EVOK", "EVRG", "EVSD", "EVTV", "EWBC", "EWCZ", "EWJV",
          "EWTX", "EWZS", "EXAI", "EXAS", "EXC", "EXE", "EXEEL", "EXEEW", "EXEEZ", "EXEL", "EXFY", "EXLS", "EXPE",
          "EXPI", "EXPO", "EXTR", "EYE", "EYEG", "EYEN", "EYPT", "EZFL", "EZGO", "EZPW", "FA", "FAAR", "FAAS", "FAASW",
          "FAB", "FAD", "FALN", "FAMI", "FANG", "FANH", "FARM", "FARO", "FAST", "FAT", "FATBB", "FATBP", "FATBW",
          "FATE", "FBIO", "FBIOP", "FBIZ", "FBL", "FBLG", "FBNC", "FBOT", "FBRX", "FBYD", "FBYDW", "FBZ", "FCA", "FCAL",
          "FCAP", "FCBC", "FCCO", "FCEF", "FCEL", "FCFS", "FCNCA", "FCNCO", "FCNCP", "FCTE", "FCUV", "FCVT", "FDBC",
          "FDCF", "FDFF", "FDIF", "FDIG", "FDIV", "FDMT", "FDNI", "FDSB", "FDT", "FDTS", "FDTX", "FDUS", "FEAM", "FEBO",
          "FEIM", "FELE", "FEM", "FEMB", "FEMS", "FEMY", "FENC", "FEP", "FEPI", "FER", "FEUZ", "FEX", "FFBC", "FFIC",
          "FFIE", "FFIEW", "FFIN", "FFIV", "FFNW", "FGBI", "FGBIP", "FGEN", "FGF", "FGFPP", "FGI", "FGIWW", "FGM",
          "FHB", "FHTX", "FIAC", "FIACU", "FIACW", "FIBK", "FICS", "FID", "FINE", "FINW", "FINX", "FIP", "FISI", "FITB",
          "FITBI", "FITBO", "FITBP", "FIVE", "FIVN", "FIXD", "FIXT", "FIZZ", "FJP", "FKU", "FKWL", "FLD", "FLDB",
          "FLDDU", "FLDDW", "FLEX", "FLGC", "FLGT", "FLIC", "FLL", "FLN", "FLNC", "FLNT", "FLUX", "FLWS", "FLX", "FLXS",
          "FLYE", "FLYW", "FMAO", "FMB", "FMBH", "FMED", "FMET", "FMHI", "FMNB", "FMST", "FMSTW", "FNGR", "FNK", "FNKO",
          "FNLC", "FNVT", "FNVTU", "FNVTW", "FNWB", "FNWD", "FNX", "FNY", "FOLD", "FONR", "FORA", "FORD", "FORL",
          "FORLU", "FORLW", "FORM", "FORR", "FORTY", "FOSL", "FOSLL", "FOX", "FOXA", "FOXF", "FOXX", "FOXXW", "FPA",
          "FPAY", "FPXE", "FPXI", "FRAF", "FRBA", "FRES", "FRGT", "FRHC", "FRLA", "FRLAU", "FRLAW", "FRME", "FRMEP",
          "FROG", "FRPH", "FRPT", "FRSH", "FRST", "FRSX", "FRZA", "FSBC", "FSBW", "FSCS", "FSEA", "FSFG", "FSHP",
          "FSHPR", "FSHPU", "FSLR", "FSTR", "FSUN", "FSV", "FSZ", "FTA", "FTAG", "FTAI", "FTAIM", "FTAIN", "FTAIO",
          "FTAIP", "FTC", "FTCI", "FTCS", "FTDR", "FTDS", "FTEK", "FTEL", "FTFT", "FTGC", "FTGS", "FTHI", "FTHM",
          "FTII", "FTIIU", "FTIIW", "FTLF", "FTNT", "FTQI", "FTRE", "FTRI", "FTSL", "FTSM", "FTXG", "FTXH", "FTXL",
          "FTXN", "FTXO", "FTXR", "FUFU", "FUFUW", "FULC", "FULT", "FULTP", "FUNC", "FUND", "FUSB", "FUTU", "FV", "FVC",
          "FVCB", "FVNNU", "FWONA", "FWONK", "FWRD", "FWRG", "FXNC", "FYBR", "FYC", "FYT", "FYX", "GABC", "GAIA",
          "GAIN", "GAINL", "GAINN", "GAINZ", "GALT", "GAMB", "GAME", "GAN", "GANX", "GAQ", "GASS", "GATE", "GATEU",
          "GATEW", "GAUZ", "GBBK", "GBBKR", "GBBKW", "GBDC", "GBIO", "GBNY", "GCBC", "GCMG", "GCMGW", "GCT", "GCTK",
          "GDC", "GDEN", "GDEV", "GDEVW", "GDHG", "GDRX", "GDS", "GDST", "GDSTR", "GDSTU", "GDSTW", "GDTC", "GDYN",
          "GECC", "GECCH", "GECCI", "GECCM", "GECCO", "GECCZ", "GEG", "GEGGL", "GEHC", "GEN", "GENE", "GENK", "GEOS",
          "GERN", "GEVO", "GFAI", "GFAIW", "GFGF", "GFS", "GGAL", "GGLL", "GGLS", "GGR", "GGROW", "GH", "GHIX", "GHIXU",
          "GHIXW", "GHRS", "GHSI", "GIFI", "GIFT", "GIG", "GIGGU", "GIGGW", "GIGM", "GIII", "GILD", "GILT", "GINX",
          "GIPR", "GIPRW", "GLAC", "GLACR", "GLACU", "GLAD", "GLADZ", "GLBE", "GLBS", "GLBZ", "GLDD", "GLDI", "GLE",
          "GLLI", "GLLIR", "GLLIU", "GLLIW", "GLMD", "GLNG", "GLOW", "GLPG", "GLPI", "GLRE", "GLSI", "GLST", "GLSTR",
          "GLSTU", "GLSTW", "GLTO", "GLUE", "GLXG", "GLYC", "GMAB", "GMGI", "GMM", "GNFT", "GNLN", "GNLX", "GNMA",
          "GNOM", "GNPX", "GNSS", "GNTA", "GNTX", "GO", "GOCO", "GODN", "GODNR", "GODNU", "GOEV", "GOEVW", "GOGL",
          "GOGO", "GOOD", "GOODN", "GOODO", "GOOG", "GOOGL", "GORV", "GOSS", "GOVI", "GOVX", "GOVXW", "GP", "GPAT",
          "GPATU", "GPATW", "GPCR", "GPIQ", "GPIX", "GPRE", "GPRF", "GPRO", "GQQQ", "GRAB", "GRABW", "GRAL", "GRDI",
          "GRDIW", "GREE", "GREEL", "GRFS", "GRI", "GRID", "GRNQ", "GROW", "GRPN", "GRRR", "GRRRW", "GRTS", "GRVY",
          "GRWG", "GRYP", "GSBC", "GSHD", "GSIB", "GSIT", "GSIW", "GSM", "GSMGW", "GSUN", "GT", "GTAC", "GTACU",
          "GTACW", "GTBP", "GTEC", "GTI", "GTIM", "GTLB", "GTR", "GTX", "GURE", "GUTS", "GV", "GVH", "GVP", "GWAV",
          "GWRS", "GXAI", "GXTG", "GYRE", "GYRO", "HAFC", "HAIA", "HAIAU", "HAIAW", "HAIN", "HALO", "HAO", "HAS",
          "HAYN", "HBAN", "HBANL", "HBANM", "HBANP", "HBCP", "HBIO", "HBNC", "HBT", "HCAT", "HCKT", "HCM", "HCOW",
          "HCP", "HCSG", "HCTI", "HCVI", "HCVIU", "HCVIW", "HCWB", "HDL", "HDSN", "HEAR", "HECO", "HEES", "HEJD",
          "HELE", "HEPA", "HEPS", "HERD", "HERO", "HFBL", "HFFG", "HFWA", "HGBL", "HHS", "HIDE", "HIFS", "HIHO", "HIMX",
          "HISF", "HITI", "HIVE", "HKIT", "HLAL", "HLIT", "HLMN", "HLNE", "HLP", "HLVX", "HLXB", "HMNF", "HMST", "HNDL",
          "HNNA", "HNNAZ", "HNRG", "HNST", "HNVR", "HOFT", "HOFV", "HOFVW", "HOLO", "HOLOW", "HOLX", "HON", "HONDU",
          "HONE", "HOOD", "HOOK", "HOPE", "HOTH", "HOUR", "HOVNP", "HOVR", "HOVRW", "HOWL", "HPAI", "HPAIW", "HPH",
          "HPK", "HPKEW", "HQGO", "HQI", "HQY", "HRMY", "HROW", "HROWL", "HROWM", "HRTS", "HRTX", "HRYU", "HRZN",
          "HSAI", "HSCS", "HSCSW", "HSDT", "HSIC", "HSII", "HSON", "HSPO", "HSPOR", "HSPOU", "HSPOW", "HST", "HSTM",
          "HTBI", "HTBK", "HTCO", "HTCR", "HTHT", "HTIA", "HTIBP", "HTLD", "HTLF", "HTLFP", "HTLM", "HTOO", "HTOOW",
          "HTZ", "HTZWW", "HUBC", "HUBCW", "HUBCZ", "HUBG", "HUDA", "HUDAR", "HUDAU", "HUDI", "HUIZ", "HUMA", "HUMAW",
          "HURC", "HURN", "HUT", "HWAY", "HWBK", "HWC", "HWCPZ", "HWH", "HWKN", "HYBI", "HYDR", "HYFM", "HYLS", "HYMC",
          "HYMCL", "HYMCW", "HYPR", "HYXF", "HYZD", "HYZN", "HYZNW", "IAC", "IART", "IAS", "IBAC", "IBACR", "IBAT",
          "IBB", "IBBQ", "IBCP", "IBEX", "IBG", "IBGA", "IBGK", "IBIT", "IBKR", "IBOC", "IBOT", "IBRX", "IBTE", "IBTF",
          "IBTG", "IBTH", "IBTI", "IBTJ", "IBTK", "IBTL", "IBTM", "IBTO", "IBTP", "IBTX", "ICAD", "ICCC", "ICCH",
          "ICCM", "ICCT", "ICFI", "ICG", "ICHR", "ICLK", "ICLN", "ICLR", "ICMB", "ICON", "ICOP", "ICU", "ICUCW", "ICUI",
          "IDAI", "IDCC", "IDN", "IDXX", "IDYA", "IEF", "IEI", "IEP", "IESC", "IEUS", "IFBD", "IFGL", "IFRX", "IFV",
          "IGF", "IGIB", "IGIC", "IGMS", "IGOV", "IGSB", "IGTA", "IGTAR", "IGTAU", "IGTAW", "IHRT", "IHYF", "III",
          "IIIV", "IINN", "IINNW", "IJT", "IKNA", "IKT", "ILAG", "ILIT", "ILMN", "ILPT", "IMAB", "IMCC", "IMCR", "IMCV",
          "IMKTA", "IMMP", "IMMR", "IMMX", "IMNM", "IMNN", "IMOM", "IMOS", "IMPP", "IMPPP", "IMRN", "IMRX", "IMTE",
          "IMTX", "IMTXW", "IMUX", "IMVT", "IMXI", "INAB", "INAQ", "INAQU", "INAQW", "INBK", "INBKZ", "INBS", "INBX",
          "INCR", "INCY", "INDB", "INDH", "INDI", "INDP", "INDV", "INDY", "INFN", "INFR", "INGN", "INHD", "INKT", "INM",
          "INMB", "INMD", "INNV", "INO", "INOD", "INRO", "INSE", "INSG", "INSM", "INTA", "INTC", "INTE", "INTEU",
          "INTEW", "INTG", "INTJ", "INTR", "INTS", "INTU", "INTZ", "INV", "INVA", "INVE", "INVO", "INVZ", "INVZW",
          "INZY", "IOBT", "IONR", "IONS", "IOSP", "IOVA", "IPA", "IPAR", "IPDN", "IPGP", "IPHA", "IPKW", "IPSC", "IPW",
          "IPWR", "IPX", "IPXX", "IPXXU", "IPXXW", "IQ", "IQQQ", "IRBT", "IRDM", "IREN", "IRIX", "IRMD", "IROH",
          "IROHR", "IROHU", "IROHW", "IRON", "IROQ", "IRTC", "IRWD", "ISHG", "ISHP", "ISPC", "ISPO", "ISPOW", "ISPR",
          "ISRG", "ISRL", "ISRLU", "ISRLW", "ISSC", "ISTB", "ISTR", "ITCI", "ITI", "ITIC", "ITOS", "ITRI", "ITRM",
          "ITRN", "IUS", "IUSB", "IUSG", "IUSV", "IVA", "IVAC", "IVAL", "IVCA", "IVCAU", "IVCAW", "IVCB", "IVCBU",
          "IVCBW", "IVCP", "IVCPU", "IVCPW", "IVDA", "IVDAW", "IVEG", "IVP", "IVVD", "IWTR", "IXAQ", "IXAQU", "IXAQW",
          "IXHL", "IXUS", "IZEA", "IZM", "JACK", "JAGX", "JAKK", "JAMF", "JANX", "JAZZ", "JBDI", "JBHT", "JBLU", "JBSS",
          "JCSE", "JCTCF", "JD", "JDOC", "JDZG", "JEPQ", "JFBR", "JFBRW", "JFIN", "JFU", "JG", "JGLO", "JIVE", "JJSF",
          "JKHY", "JL", "JMID", "JMSB", "JNVR", "JOUT", "JPEF", "JRSH", "JRVR", "JSM", "JSMD", "JSML", "JSPR", "JSPRW",
          "JTAI", "JTEK", "JUNE", "JVA", "JVSA", "JVSAR", "JVSAU", "JWEL", "JXJT", "JYD", "JYNT", "JZ", "JZXN", "KACL",
          "KACLR", "KACLU", "KACLW", "KALA", "KALU", "KALV", "KARO", "KAVL", "KBWB", "KBWD", "KBWP", "KBWR", "KBWY",
          "KC", "KDLY", "KDLYW", "KDP", "KE", "KEAT", "KELYA", "KELYB", "KEQU", "KFFB", "KGEI", "KHC", "KIDS", "KINS",
          "KIRK", "KITT", "KITTW", "KLAC", "KLIC", "KLTO", "KLTOW", "KLTR", "KLXE", "KMDA", "KNDI", "KNGZ", "KNSA",
          "KOD", "KOPN", "KOSS", "KPLT", "KPLTW", "KPRX", "KPTI", "KQQQ", "KRKR", "KRMA", "KRMD", "KRNT", "KRNY",
          "KRON", "KROP", "KROS", "KRRO", "KRT", "KRUS", "KRYS", "KSCP", "KSPI", "KTCC", "KTOS", "KTRA", "KTTA",
          "KTTAW", "KURA", "KVAC", "KVACU", "KVACW", "KVHI", "KWE", "KWESW", "KXIN", "KYMR", "KYTX", "KZIA", "KZR",
          "LAB", "LAES", "LAKE", "LAMR", "LANC", "LAND", "LANDM", "LANDO", "LANDP", "LARK", "LASE", "LASR", "LATG",
          "LATGU", "LAUR", "LAZR", "LBPH", "LBRDA", "LBRDK", "LBRDP", "LBTYA", "LBTYB", "LBTYK", "LCDS", "LCFY",
          "LCFYW", "LCID", "LCNB", "LCUT", "LDEM", "LDSF", "LDTC", "LDTCW", "LDWY", "LE", "LECO", "LEDS", "LEE", "LEGH",
          "LEGN", "LEGR", "LENZ", "LESL", "LEXX", "LEXXW", "LFCR", "LFLY", "LFLYW", "LFMD", "LFMDP", "LFST", "LFUS",
          "LFVN", "LFWD", "LGCB", "LGCL", "LGHL", "LGHLW", "LGIH", "LGMK", "LGND", "LGO", "LGRO", "LGTY", "LGVN", "LI",
          "LICN", "LIDR", "LIDRW", "LIEN", "LIF", "LIFW", "LIFWW", "LIFWZ", "LILA", "LILAK", "LILM", "LILMW", "LIN",
          "LINC", "LIND", "LINE", "LINK", "LION", "LIPO", "LIQT", "LITE", "LITM", "LITP", "LIVE", "LIVN", "LIVR",
          "LIXT", "LIXTW", "LKCO", "LKFN", "LKQ", "LLYVA", "LLYVK", "LMAT", "LMB", "LMBS", "LMFA", "LMNR", "LNKB",
          "LNSR", "LNT", "LNTH", "LNW", "LNZA", "LNZAW", "LOAN", "LOBO", "LOCO", "LOGC", "LOGI", "LOOP", "LOPE", "LOT",
          "LOTWW", "LOVE", "LPAA", "LPAAU", "LPAAW", "LPCN", "LPLA", "LPRO", "LPSN", "LPTH", "LPTX", "LQDA", "LQDT",
          "LQR", "LRCX", "LRE", "LRFC", "LRGE", "LRHC", "LRMR", "LRND", "LSAK", "LSB", "LSBK", "LSBPW", "LSCC", "LSEA",
          "LSEAW", "LSH", "LSTA", "LSTR", "LTBR", "LTRN", "LTRX", "LTRY", "LTRYW", "LUCD", "LUCY", "LUCYW", "LULU",
          "LUMO", "LUNA", "LUNG", "LUNR", "LUNRW", "LUXH", "LUXHP", "LVHD", "LVLU", "LVO", "LVRO", "LVROW", "LVTX",
          "LWAY", "LWLG", "LX", "LXEH", "LXEO", "LXRX", "LYEL", "LYFT", "LYRA", "LYT", "LYTS", "LZ", "MACI", "MACIU",
          "MACIW", "MAGQ", "MAGS", "MAGX", "MAMA", "MAMO", "MANH", "MAPS", "MAPSW", "MAR", "MARA", "MARPS", "MARX",
          "MARXR", "MARXU", "MASI", "MASS", "MAT", "MATH", "MATW", "MAXI", "MAXN", "MAYS", "MBAV", "MBAVU", "MBAVW",
          "MBB", "MBCN", "MBIN", "MBINM", "MBINN", "MBINO", "MBIO", "MBLY", "MBNKP", "MBOT", "MBRX", "MBUU", "MBWM",
          "MBX", "MCAA", "MCAAU", "MCAAW", "MCAG", "MCAGR", "MCAGU", "MCBS", "MCDS", "MCFT", "MCHI", "MCHP", "MCHS",
          "MCHX", "MCRB", "MCRI", "MCSE", "MCVT", "MDAI", "MDAIW", "MDB", "MDBH", "MDCP", "MDGL", "MDIA", "MDIV",
          "MDJH", "MDLZ", "MDRR", "MDRRP", "MDWD", "MDXG", "MDXH", "ME", "MEDP", "MEDX", "MEGL", "MEIP", "MELI", "MEMS",
          "MEOH", "MERC", "MESA", "MESO", "META", "METC", "METCB", "METCL", "METD", "METU", "MFH", "MFI", "MFIC",
          "MFICL", "MFIN", "MFLX", "MGEE", "MGIC", "MGIH", "MGNI", "MGNX", "MGOL", "MGPI", "MGRC", "MGRM", "MGRX",
          "MGTX", "MGX", "MGYR", "MHLD", "MHUA", "MIDD", "MIGI", "MILN", "MIND", "MIRA", "MIRM", "MIST", "MITA",
          "MITAU", "MITAW", "MITK", "MKAM", "MKDW", "MKDWW", "MKSI", "MKTW", "MKTX", "MLAB", "MLCO", "MLEC", "MLECW",
          "MLGO", "MLKN", "MLTX", "MLYS", "MMLP", "MMSI", "MMV", "MMVWW", "MMYT", "MNDO", "MNDR", "MNDY", "MNKD",
          "MNMD", "MNOV", "MNPR", "MNRO", "MNSB", "MNSBP", "MNST", "MNTK", "MNTL", "MNTS", "MNTSW", "MNTX", "MNY",
          "MNYWW", "MOB", "MOBBW", "MOBX", "MOBXW", "MODD", "MODL", "MODV", "MOFG", "MOGO", "MOLN", "MOMO", "MOND",
          "MOOD", "MORN", "MOVE", "MPAA", "MPB", "MPWR", "MQ", "MQQQ", "MRAM", "MRBK", "MRCC", "MRCY", "MREO", "MRIN",
          "MRKR", "MRM", "MRNA", "MRNO", "MRNOW", "MRNS", "MRSN", "MRTN", "MRUS", "MRVI", "MRVL", "MRX", "MSAI",
          "MSAIW", "MSBI", "MSBIP", "MSEX", "MSFD", "MSFL", "MSFT", "MSFU", "MSGM", "MSS", "MSSA", "MSSAR", "MSSAU",
          "MSSAW", "MSTR", "MSTX", "MTC", "MTCH", "MTEK", "MTEKW", "MTEM", "MTEN", "MTEX", "MTLS", "MTRX", "MTSI",
          "MTTR", "MU", "MULN", "MURA", "MVBF", "MVIS", "MVST", "MVSTW", "MXCT", "MXL", "MYCF", "MYCG", "MYCH", "MYCI",
          "MYCJ", "MYCK", "MYCL", "MYCM", "MYCN", "MYFW", "MYGN", "MYMF", "MYMG", "MYMH", "MYMI", "MYMJ", "MYNA",
          "MYNZ", "MYPS", "MYPSW", "MYRG", "MYSZ", "NA", "NAAS", "NAII", "NAMS", "NAMSW", "NAOV", "NARI", "NATH",
          "NATR", "NAUT", "NAVI", "NB", "NBBK", "NBIS", "NBIX", "NBN", "NBTB", "NBTX", "NCI", "NCMI", "NCNA", "NCNC",
          "NCNCW", "NCNO", "NCPB", "NCPL", "NCPLW", "NCRA", "NCSM", "NCTY", "NDAQ", "NDLS", "NDRA", "NDSN", "NECB",
          "NEGG", "NEO", "NEOG", "NEON", "NEOV", "NEOVW", "NEPH", "NERD", "NERV", "NETD", "NETDU", "NETDW", "NEWT",
          "NEWTG", "NEWTH", "NEWTI", "NEWTZ", "NEWZ", "NEXN", "NEXT", "NFBK", "NFE", "NFLX", "NFTY", "NFXL", "NFXS",
          "NGNE", "NHTC", "NICE", "NIKL", "NIOBW", "NIPG", "NISN", "NITO", "NIU", "NIVF", "NIVFW", "NIXT", "NIXX",
          "NIXXW", "NKGN", "NKGNW", "NKLA", "NKSH", "NKTR", "NKTX", "NLSP", "NLSPW", "NMFC", "NMFCZ", "NMHI", "NMHIW",
          "NMIH", "NMRA", "NMRK", "NMTC", "NN", "NNAVW", "NNBR", "NNDM", "NNE", "NNOX", "NODK", "NOTV", "NOVT", "NOVV",
          "NOVVR", "NOVVU", "NOVVW", "NPAB", "NPABU", "NPABW", "NPCE", "NPFI", "NRBO", "NRC", "NRDS", "NRES", "NRIM",
          "NRIX", "NRSN", "NRSNW", "NRXP", "NRXPW", "NSCR", "NSI", "NSIT", "NSPR", "NSSC", "NSTS", "NSYS", "NTAP",
          "NTBL", "NTCT", "NTES", "NTGR", "NTIC", "NTLA", "NTNX", "NTRA", "NTRB", "NTRBW", "NTRP", "NTRS", "NTRSO",
          "NTWK", "NTZG", "NUKK", "NUKKW", "NURO", "NUSB", "NUTX", "NUVL", "NUWE", "NUZE", "NVA", "NVAC", "NVACR",
          "NVACW", "NVAWW", "NVAX", "NVCR", "NVCT", "NVD", "NVDA", "NVDD", "NVDL", "NVDS", "NVDU", "NVDW", "NVEC",
          "NVEE", "NVEI", "NVFY", "NVMI", "NVNI", "NVNIW", "NVNO", "NVOS", "NVTS", "NVVE", "NVVEW", "NVX", "NWBI",
          "NWE", "NWFL", "NWGL", "NWL", "NWPX", "NWS", "NWSA", "NWTN", "NWTNW", "NXGL", "NXGLW", "NXL", "NXLIW", "NXPI",
          "NXPL", "NXPLW", "NXST", "NXT", "NXTC", "NXTG", "NXTT", "NXU", "NYAX", "NYMT", "NYMTI", "NYMTL", "NYMTM",
          "NYMTN", "NYMTZ", "NYXH", "NZAC", "NZUS", "OABI", "OABIW", "OAKU", "OAKUR", "OAKUU", "OAKUW", "OB", "OBIL",
          "OBIO", "OBLG", "OBT", "OCC", "OCCI", "OCCIM", "OCCIN", "OCCIO", "OCEA", "OCEAW", "OCFC", "OCFCP", "OCG",
          "OCGN", "OCS", "OCSAW", "OCSL", "OCTA", "OCTO", "OCUL", "OCUP", "OCX", "ODD", "ODDS", "ODFL", "ODP", "ODVWZ",
          "OESX", "OFIX", "OFLX", "OFS", "OFSSH", "OGI", "OKTA", "OKYO", "OLB", "OLED", "OLLI", "OLMA", "OLPX", "OM",
          "OMAB", "OMCC", "OMCL", "OMER", "OMEX", "OMGA", "OMH", "OMIC", "ON", "ONB", "ONBPO", "ONBPP", "ONCO", "ONCT",
          "ONCY", "ONDS", "ONEQ", "ONEW", "ONFO", "ONFOW", "ONMD", "ONMDW", "ONVO", "ONYX", "ONYXU", "ONYXW", "OP",
          "OPAL", "OPBK", "OPCH", "OPEN", "OPHC", "OPI", "OPINL", "OPK", "OPOF", "OPRA", "OPRT", "OPRX", "OPT", "OPTN",
          "OPTX", "OPTXW", "OPTZ", "OPXS", "ORGN", "ORGNW", "ORGO", "ORGS", "ORIC", "ORKA", "ORKT", "ORLY", "ORMP",
          "ORRF", "OS", "OSBC", "OSIS", "OSPN", "OSS", "OST", "OSUR", "OSW", "OTEX", "OTLK", "OTLY", "OTRK", "OTTR",
          "OVBC", "OVID", "OVLY", "OXBR", "OXBRW", "OXLC", "OXLCI", "OXLCL", "OXLCN", "OXLCO", "OXLCP", "OXLCZ", "OXSQ",
          "OXSQG", "OXSQZ", "OZEM", "OZK", "OZKAP", "PAA", "PABD", "PABU", "PACB", "PAGP", "PAHC", "PAL", "PALI",
          "PALT", "PANL", "PANW", "PARA", "PARAA", "PASG", "PATK", "PATN", "PAVM", "PAVMZ", "PAVS", "PAX", "PAYO",
          "PAYS", "PAYX", "PBBK", "PBFS", "PBHC", "PBM", "PBMWW", "PBPB", "PBYI", "PC", "PCAR", "PCB", "PCH", "PCRX",
          "PCSA", "PCSC", "PCT", "PCTTU", "PCTTW", "PCTY", "PCVX", "PCYO", "PDBA", "PDBC", "PDCO", "PDD", "PDEX",
          "PDFS", "PDLB", "PDP", "PDSB", "PDYN", "PDYNW", "PEBK", "PEBO", "PECO", "PEGA", "PEGY", "PENN", "PEP", "PEPG",
          "PERI", "PESI", "PET", "PETQ", "PETS", "PETWW", "PETZ", "PEV", "PEY", "PEZ", "PFBC", "PFC", "PFF", "PFG",
          "PFI", "PFIE", "PFIS", "PFM", "PFMT", "PFTA", "PFTAU", "PFTAW", "PFX", "PFXNZ", "PGC", "PGEN", "PGHL", "PGJ",
          "PGNY", "PGY", "PGYWW", "PHAR", "PHAT", "PHIO", "PHO", "PHUN", "PHVS", "PI", "PID", "PIE", "PIII", "PIIIW",
          "PIK", "PINC", "PIO", "PIRS", "PITA", "PITAW", "PIXY", "PIZ", "PKBK", "PKOH", "PKW", "PLAB", "PLAO", "PLAOU",
          "PLAOW", "PLAY", "PLBC", "PLBY", "PLCE", "PLL", "PLMJ", "PLMJU", "PLMJW", "PLMR", "PLPC", "PLRX", "PLSE",
          "PLTK", "PLUG", "PLUR", "PLUS", "PLXS", "PLYA", "PMAX", "PMBS", "PMCB", "PMD", "PMEC", "PMN", "PMTS", "PMVP",
          "PNBK", "PNFP", "PNFPP", "PNQI", "PNRG", "PNTG", "POAI", "POCI", "PODC", "PODD", "POET", "POLA", "POLEU",
          "POOL", "POWI", "POWL", "POWW", "POWWP", "PPBI", "PPBT", "PPC", "PPH", "PPIH", "PPSI", "PPTA", "PPYA",
          "PPYAU", "PPYAW", "PRAA", "PRAX", "PRCH", "PRCT", "PRDO", "PRE", "PRENW", "PRFX", "PRFZ", "PRGS", "PRLD",
          "PRLH", "PRLHU", "PRLHW", "PRME", "PRN", "PROC", "PROCW", "PROF", "PROK", "PROP", "PROV", "PRPH", "PRPL",
          "PRPO", "PRQR", "PRSO", "PRTA", "PRTC", "PRTG", "PRTH", "PRTS", "PRVA", "PRZO", "PSC", "PSCC", "PSCD", "PSCE",
          "PSCF", "PSCH", "PSCI", "PSCM", "PSCT", "PSCU", "PSEC", "PSET", "PSHG", "PSIG", "PSL", "PSMT", "PSNL", "PSNY",
          "PSNYW", "PSTR", "PSTV", "PSTX", "PSWD", "PT", "PTC", "PTCT", "PTEC", "PTEN", "PTF", "PTGX", "PTH", "PTHL",
          "PTIR", "PTIX", "PTIXW", "PTLO", "PTMN", "PTNQ", "PTON", "PTPI", "PTSI", "PTVE", "PUBM", "PUI", "PULM",
          "PVBC", "PWM", "PWOD", "PWP", "PWUP", "PWUPU", "PWUPW", "PXDT", "PXI", "PXLW", "PXS", "PXSAP", "PXSAW", "PY",
          "PYCR", "PYPD", "PYPL", "PYXS", "PYZ", "PZZA", "QABA", "QAT", "QBUF", "QCLN", "QCLR", "QCOM", "QCRH", "QDEL",
          "QETA", "QETAR", "QETAU", "QFIN", "QH", "QHDG", "QIPT", "QLGN", "QLYS", "QMCO", "QMID", "QMMM", "QMOM",
          "QNCX", "QNRX", "QNST", "QNTM", "QOMO", "QOMOR", "QOMOU", "QOMOW", "QOWZ", "QQA", "QQEW", "QQJG", "QQMG",
          "QQQ", "QQQA", "QQQE", "QQQG", "QQQI", "QQQJ", "QQQM", "QQQN", "QQQP", "QQQS", "QQQT", "QQQW", "QQQX", "QQQY",
          "QQXT", "QRHC", "QRMI", "QRTEA", "QRTEB", "QRTEP", "QRVO", "QSG", "QSI", "QSIAW", "QSIX", "QSML", "QTEC",
          "QTI", "QTR", "QTRX", "QTTB", "QTUM", "QUBT", "QUIK", "QURE", "QVAL", "QXO", "QXQ", "QYLD", "QYLE", "QYLG",
          "RAIL", "RAND", "RANI", "RAPP", "RAPT", "RARE", "RAVE", "RAY", "RAYA", "RAYS", "RBB", "RBBN", "RBCAA", "RBKB",
          "RCAT", "RCEL", "RCKT", "RCKTW", "RCKY", "RCM", "RCMT", "RCON", "RDCM", "RDFN", "RDHL", "RDI", "RDIB", "RDNT",
          "RDUS", "RDVT", "RDVY", "RDWR", "RDZN", "RDZNW", "REAI", "REAL", "REAX", "REBN", "RECT", "REE", "REFI",
          "REFR", "REG", "REGCO", "REGCP", "REGN", "REIT", "REKR", "RELI", "RELIW", "RELL", "RELY", "RENB", "RENE",
          "RENEU", "RENEW", "RENT", "REPL", "RETO", "REVB", "REVBW", "REYN", "RFAC", "RFACR", "RFACU", "RFACW", "RFAI",
          "RFAIR", "RFAIU", "RFDI", "RFEM", "RFEU", "RFIL", "RGC", "RGCO", "RGEN", "RGF", "RGLD", "RGLS", "RGNX", "RGP",
          "RGS", "RGTI", "RGTIW", "RICK", "RIGL", "RILY", "RILYG", "RILYK", "RILYL", "RILYM", "RILYN", "RILYP", "RILYT",
          "RILYZ", "RIME", "RING", "RIOT", "RITR", "RIVN", "RKDA", "RKLB", "RLAY", "RLMD", "RLYB", "RMBI", "RMBL",
          "RMBS", "RMCF", "RMCO", "RMCOW", "RMNI", "RMR", "RMTI", "RNA", "RNAC", "RNAZ", "RNEM", "RNEW", "RNLX", "RNRG",
          "RNSC", "RNW", "RNWWW", "RNXT", "ROAD", "ROBT", "ROCK", "ROCL", "ROCLU", "ROCLW", "ROE", "ROIC", "ROIV",
          "ROKU", "ROMA", "ROOT", "ROP", "ROST", "RPAY", "RPD", "RPHM", "RPID", "RPRX", "RPTX", "RR", "RRBI", "RRGB",
          "RRR", "RSLS", "RSSS", "RSVR", "RSVRW", "RTC", "RTH", "RUM", "RUMBW", "RUN", "RUNN", "RUSHA", "RUSHB", "RVMD",
          "RVMDW", "RVNC", "RVPH", "RVPHW", "RVSB", "RVSN", "RVSNW", "RVYL", "RWAY", "RWAYL", "RWAYZ", "RXRX", "RXST",
          "RXT", "RYAAY", "RYTM", "RZLT", "RZLV", "RZLVW", "SABR", "SABS", "SABSW", "SAFT", "SAGE", "SAIA", "SAIC",
          "SAIH", "SAIHW", "SAMG", "SANA", "SANG", "SANM", "SANW", "SARK", "SASR", "SATL", "SATLW", "SATS", "SAVA",
          "SBAC", "SBC", "SBCF", "SBCWW", "SBET", "SBFG", "SBFM", "SBFMW", "SBGI", "SBLK", "SBRA", "SBSI", "SBT",
          "SBUX", "SCDS", "SCHL", "SCKT", "SCLX", "SCLXW", "SCNI", "SCNX", "SCOR", "SCPH", "SCSC", "SCVL", "SCWO",
          "SCWX", "SCYX", "SCZ", "SDA", "SDAWW", "SDG", "SDGR", "SDIG", "SDOT", "SDSI", "SDST", "SDSTW", "SDVY", "SEAT",
          "SEATW", "SEDG", "SEED", "SEEL", "SEER", "SEIC", "SELF", "SELX", "SENEA", "SENEB", "SERA", "SERV", "SETM",
          "SEVN", "SEZL", "SFBC", "SFIX", "SFLO", "SFM", "SFNC", "SFST", "SFWL", "SGA", "SGBX", "SGC", "SGD", "SGH",
          "SGHT", "SGLY", "SGMA", "SGML", "SGMO", "SGMT", "SGRP", "SGRY", "SHBI", "SHC", "SHCR", "SHCRW", "SHEN",
          "SHFS", "SHFSW", "SHIM", "SHIP", "SHLS", "SHLT", "SHMD", "SHMDW", "SHOO", "SHOT", "SHOTW", "SHPH", "SHRY",
          "SHV", "SHY", "SHYF", "SIBN", "SIDU", "SIEB", "SIFY", "SIGA", "SIGI", "SIGIP", "SILC", "SILO", "SIMA",
          "SIMAU", "SIMAW", "SIMO", "SINT", "SIRI", "SISI", "SITM", "SIXG", "SJ", "SJCP", "SJLD", "SKGR", "SKGRU",
          "SKGRW", "SKIN", "SKOR", "SKRE", "SKWD", "SKYE", "SKYT", "SKYU", "SKYW", "SKYX", "SKYY", "SLAB", "SLDB",
          "SLDP", "SLDPW", "SLE", "SLGL", "SLM", "SLMBP", "SLN", "SLNG", "SLNH", "SLNHP", "SLNO", "SLP", "SLQD", "SLRC",
          "SLRN", "SLRX", "SLS", "SLVO", "SLXN", "SLXNW", "SMBC", "SMCF", "SMCI", "SMCO", "SMCP", "SMCX", "SMH", "SMHX",
          "SMID", "SMLR", "SMMT", "SMPL", "SMRI", "SMSI", "SMST", "SMTC", "SMTI", "SMTK", "SMX", "SMXT", "SMXWW",
          "SNAL", "SNAX", "SNAXW", "SNBR", "SNCR", "SNCRL", "SNCY", "SND", "SNDL", "SNDX", "SNES", "SNEX", "SNFCA",
          "SNGX", "SNOA", "SNPS", "SNPX", "SNSE", "SNSR", "SNT", "SNTG", "SNTI", "SNY", "SOBR", "SOCL", "SOFI", "SOGP",
          "SOHO", "SOHOB", "SOHON", "SOHOO", "SOHU", "SOND", "SONDW", "SONM", "SONN", "SONO", "SOPA", "SOPH", "SOTK",
          "SOUN", "SOUNW", "SOWG", "SOXM", "SOXQ", "SOXW", "SOXX", "SPAI", "SPAM", "SPAQ", "SPBC", "SPC", "SPCB",
          "SPCX", "SPFI", "SPGC", "SPI", "SPKL", "SPKLU", "SPKLW", "SPNS", "SPOK", "SPPL", "SPRB", "SPRC", "SPRO",
          "SPRX", "SPRY", "SPSC", "SPT", "SPTN", "SPWH", "SPYB", "SPYM", "SPYQ", "SQFT", "SQFTP", "SQFTW", "SQLV",
          "SQQQ", "SRAD", "SRBK", "SRCE", "SRCL", "SRDX", "SRET", "SRM", "SRPT", "SRRK", "SRTS", "SRZN", "SRZNW",
          "SSBI", "SSBK", "SSKN", "SSNC", "SSP", "SSRM", "SSSS", "SSSSL", "SSTI", "SSYS", "STAA", "STAF", "STBA",
          "STBX", "STCN", "STEC", "STEP", "STER", "STGW", "STHO", "STI", "STIM", "STKH", "STKL", "STKS", "STLD", "STNE",
          "STOK", "STRA", "STRL", "STRM", "STRO", "STRR", "STRRP", "STRS", "STRT", "STSS", "STSSW", "STTK", "STX",
          "SUGP", "SUNS", "SUPN", "SURG", "SURGW", "SUSB", "SUSC", "SUSL", "SUUN", "SVA", "SVC", "SVCO", "SVII",
          "SVIIR", "SVIIU", "SVIIW", "SVMH", "SVMHW", "SVRA", "SVRE", "SVREW", "SWAG", "SWAGW", "SWBI", "SWIM", "SWIN",
          "SWKH", "SWKHL", "SWKS", "SWP", "SWTX", "SWVL", "SWVLW", "SXTC", "SXTP", "SXTPW", "SY", "SYBT", "SYBX", "SYM",
          "SYNA", "SYPR", "SYRA", "SYRE", "SYRS", "SYT", "SYTA", "SYTAW", "TACT", "TAIT", "TALK", "TALKW", "TANH",
          "TAOP", "TARA", "TARK", "TARS", "TASK", "TATT", "TAXE", "TAYD", "TBBK", "TBIL", "TBLA", "TBLAW", "TBLD",
          "TBMC", "TBMCR", "TBNK", "TBPH", "TBRG", "TC", "TCBI", "TCBIO", "TCBK", "TCBP", "TCBPW", "TCBS", "TCBX",
          "TCHI", "TCJH", "TCMD", "TCOM", "TCPC", "TCRT", "TCRX", "TCTM", "TCX", "TDI", "TDIV", "TDSB", "TDSC", "TDTH",
          "TDUP", "TEAM", "TECH", "TECTP", "TECX", "TEKX", "TELA", "TELO", "TEM", "TENB", "TENX", "TER", "TERN", "TETE",
          "TETEU", "TETEW", "TFFP", "TFIN", "TFINP", "TFSL", "TGAA", "TGAAU", "TGAAW", "TGL", "TGTX", "TH", "THAR",
          "THCH", "THCP", "THCPU", "THCPW", "THFF", "THRD", "THRM", "THRY", "THTX", "TIGO", "TIGR", "TIL", "TILE",
          "TIPT", "TIRX", "TITN", "TIVC", "TKLF", "TKNO", "TLF", "TLGY", "TLGYU", "TLGYW", "TLN", "TLPH", "TLRY", "TLS",
          "TLSA", "TLSI", "TLSIW", "TLT", "TLTM", "TLTQ", "TMC", "TMCI", "TMCWW", "TMDX", "TMET", "TMTC", "TMTCR",
          "TMTCU", "TMUS", "TNDM", "TNFA", "TNGX", "TNON", "TNONW", "TNXP", "TNYA", "TOI", "TOIIW", "TOMZ", "TOP",
          "TORO", "TOUR", "TOWN", "TOYO", "TPCS", "TPG", "TPGXL", "TPIC", "TPST", "TQQQ", "TRAW", "TRDA", "TREE",
          "TRIB", "TRIN", "TRINI", "TRINL", "TRINZ", "TRIP", "TRMB", "TRMD", "TRMK", "TRML", "TRNR", "TRNS", "TROO",
          "TROW", "TRS", "TRSG", "TRST", "TRUE", "TRUG", "TRUP", "TRVG", "TRVI", "TRVN", "TSAT", "TSBK", "TSBX", "TSCO",
          "TSDD", "TSEM", "TSHA", "TSL", "TSLA", "TSLL", "TSLQ", "TSLR", "TSLS", "TSLT", "TSLW", "TSLZ", "TSMX", "TSMZ",
          "TSPY", "TSVT", "TTD", "TTEC", "TTEK", "TTGT", "TTMI", "TTNP", "TTOO", "TTSH", "TTWO", "TUG", "TUGN", "TUR",
          "TURB", "TURN", "TUSK", "TVGN", "TVGNW", "TVTX", "TW", "TWFG", "TWG", "TWIN", "TWKS", "TWST", "TXG", "TXMD",
          "TXN", "TXRH", "TXSS", "TYGO", "TYRA", "TZOO", "UAE", "UAL", "UBCP", "UBFO", "UBND", "UBRL", "UBSI", "UBX",
          "UBXG", "UCAR", "UCL", "UCRD", "UCTT", "UCYB", "UDMY", "UEIC", "UEVM", "UFCS", "UFIV", "UFO", "UFPI", "UFPT",
          "UG", "UGRO", "UHG", "UHGWW", "UITB", "UIVM", "UK", "UKOMW", "ULBI", "ULCC", "ULH", "ULTA", "ULVM", "ULY",
          "UMBF", "UMMA", "UNB", "UNCY", "UNIT", "UNIY", "UNTY", "UONE", "UONEK", "UPBD", "UPC", "UPGR", "UPLD", "UPST",
          "UPWK", "UPXI", "URBN", "URGN", "URNJ", "UROY", "USAP", "USAU", "USCB", "USCF", "USCL", "USDX", "USEA",
          "USEG", "USFI", "USGO", "USGOW", "USIG", "USIN", "USIO", "USLM", "USMC", "USOI", "USOY", "USRD", "USSH",
          "USTB", "USVM", "USVN", "USXF", "UTEN", "UTHR", "UTHY", "UTMD", "UTRE", "UTSI", "UTWO", "UTWY", "UVSP",
          "UXIN", "VABK", "VACH", "VACHU", "VACHW", "VALN", "VALU", "VANI", "VBFC", "VBNK", "VBTX", "VC", "VCEL",
          "VCICU", "VCIG", "VCIT", "VCLT", "VCNX", "VCRB", "VCSA", "VCSH", "VCTR", "VCYT", "VECO", "VEEA", "VEEAW",
          "VEEE", "VEON", "VERA", "VERB", "VERI", "VERO", "VERU", "VERV", "VERX", "VEV", "VFF", "VFLO", "VFS", "VFSWW",
          "VGAS", "VGASW", "VGIT", "VGLT", "VGSH", "VGSR", "VIASP", "VIAV", "VICR", "VIGI", "VIGL", "VINC", "VINO",
          "VINP", "VIOT", "VIR", "VIRC", "VIRI", "VIRT", "VIRX", "VISL", "VITL", "VIVK", "VKTX", "VLCN", "VLGEA", "VLY",
          "VLYPN", "VLYPO", "VLYPP", "VMAR", "VMBS", "VMCA", "VMCAU", "VMCAW", "VMD", "VMEO", "VMOT", "VNDA", "VNET",
          "VNOM", "VNQI", "VOD", "VONE", "VONG", "VONV", "VOR", "VOXR", "VOXX", "VPLS", "VRA", "VRAR", "VRAX", "VRCA",
          "VRDN", "VREX", "VRIG", "VRM", "VRME", "VRMEW", "VRNA", "VRNS", "VRNT", "VRPX", "VRRM", "VRSK", "VRSN",
          "VRTX", "VS", "VSAC", "VSACU", "VSACW", "VSAT", "VSDA", "VSEC", "VSEE", "VSEEW", "VSME", "VSMV", "VSSYW",
          "VSTA", "VSTE", "VSTEW", "VSTM", "VTC", "VTGN", "VTHR", "VTIP", "VTNR", "VTRS", "VTSI", "VTVT", "VTWG",
          "VTWO", "VTWV", "VTYX", "VUZI", "VVOS", "VVPR", "VWOB", "VXRT", "VXUS", "VYGR", "VYMI", "VYNE", "WABC",
          "WABF", "WAFD", "WAFDP", "WAFU", "WALD", "WALDW", "WASH", "WATT", "WAVE", "WAVS", "WAVSU", "WAVSW", "WAY",
          "WB", "WBA", "WBD", "WBND", "WBTN", "WBUY", "WCBR", "WCLD", "WCT", "WDAY", "WDC", "WDFC", "WEEI", "WEN",
          "WERN", "WEST", "WESTW", "WETH", "WEYS", "WFCF", "WFRD", "WGMI", "WGS", "WGSWW", "WHF", "WHFCL", "WHLM",
          "WHLR", "WHLRD", "WHLRL", "WHLRP", "WILC", "WIMI", "WINA", "WINC", "WING", "WINT", "WINV", "WINVR", "WINVU",
          "WINVW", "WISA", "WISE", "WIX", "WKEY", "WKHS", "WKSP", "WLDN", "WLDS", "WLDSW", "WLFC", "WLGS", "WMG",
          "WMPN", "WNDY", "WNEB", "WNW", "WOK", "WOOD", "WOOF", "WORX", "WPRT", "WRAP", "WRLD", "WRND", "WSBC", "WSBCP",
          "WSBF", "WSC", "WSFS", "WTBA", "WTBN", "WTFC", "WTFCM", "WTFCP", "WTMA", "WTMAR", "WTMAU", "WTO", "WTW",
          "WULF", "WVE", "WVVI", "WVVIP", "WW", "WWD", "WYNN", "XAIR", "XAIX", "XBIL", "XBIO", "XBIT", "XBP", "XBPEW",
          "XCH", "XCNY", "XCUR", "XEL", "XELA", "XELAP", "XELB", "XENE", "XERS", "XFIX", "XFOR", "XGN", "XHG", "XLO",
          "XMTR", "XNCR", "XNET", "XOMA", "XOMAO", "XOMAP", "XOS", "XOSWW", "XOVR", "XP", "XPEL", "XPON", "XRAY",
          "XRTX", "XRX", "XT", "XTIA", "XTKG", "XTLB", "XWEL", "XXII", "XYLO", "YGMZ", "YHGJ", "YHNAU", "YI", "YIBO",
          "YJ", "YLDE", "YMAB", "YORW", "YOSH", "YOTA", "YOTAR", "YOTAU", "YOTAW", "YQ", "YQQQ", "YTRA", "YXT", "YY",
          "YYAI", "YYGH", "Z", "ZAPP", "ZAPPW", "ZAZZT", "ZBAO", "ZBIO", "ZBRA", "ZBZZT", "ZCAR", "ZCARW", "ZCMD",
          "ZCZZT", "ZD", "ZENA", "ZENV", "ZEO", "ZEOWW", "ZEUS", "ZG", "ZI", "ZIMV", "ZION", "ZIONL", "ZIONO", "ZIONP",
          "ZJK", "ZJYL", "ZJZZT", "ZKIN", "ZLAB", "ZM", "ZNTL", "ZOOZ", "ZOOZW", "ZPTA", "ZPTAW", "ZS", "ZTEK", "ZUMZ",
          "ZURA", "ZVRA", "ZVSA", "ZVZZT", "ZWZZT", "ZXYZ.A", "ZXZZT", "ZYME", "ZYXI", "ZZZ"]


def download_and_save_ticker(ticker="ITSA4.SA", start_date="2024-01-01", end_date="2024-12-31"):
    # Baixa os dados do ticker
    data = yf.Ticker(ticker).history(start=start_date, end=end_date)

    # Cria o caminho da pasta se ainda não existir
    save_path = 'database/gallywix/stocks'
    os.makedirs(save_path, exist_ok=True)

    # Define o nome do arquivo como <ticker>.csv
    file_name = f"{ticker}.csv"

    # Salva o DataFrame como um arquivo CSV
    file_path = os.path.join(save_path, file_name)
    data.to_csv(file_path)

    print(f"Dados salvos em: {file_path}")

# Testando a função
# for ticker in ticker_list:
#     download_and_save_ticker(ticker=ticker, start_date="2000-01-01", end_date="2024-12-31")
